# We keep our list of function words in a module
# Function words from Appendix 3 of Narayanan et al. 2012
function_words=set([
"aboard", "about", "above", "absent", "according", "accordingly",  "across",
"after", "against", "ahead", "albeit", "all", "along", "alongside", "although",
"am", "amid", "amidst", "among", "amongst", "amount", "an", "and", "another",
"anti",  "any", "anybody", "anyone", "anything", "are", "around", "as",
"aside", "astraddle",  "astride", "at", "away", "bar", "barring", "be",
"because", "been", "before", "behind",  "being", "below", "beneath", "beside",
"besides", "better", "between", "beyond", "bit",  "both", "but", "by", "can",
"certain", "circa", "close", "concerning", "consequently",  "considering",
"could", "couple", "dare", "deal", "despite", "down", "due", "during",  "each",
"eight", "eighth", "either", "enough", "every", "everybody", "everyone",
"everything", "except", "excepting", "excluding", "failing", "few", "fewer",
" fifth",  " first", " five", "following", "for", "four", "fourth", "from",
"front", "given", "good",  "great", "had", "half", "have", "he", "heaps",
"hence", "her", "hers", "herself", "him",  "himself", "his", "however", "i",
"if", "in", "including", "inside", "instead", "into", "is", "it",  "its",
"itself", "keeping", "lack", "less", "like", "little", "loads", "lots",
"majority", "many",  "masses", "may", "me", "might", "mine", "minority",
"minus", "more", "most", "much",  "must", "my", "myself", "near", "need",
"neither", "nevertheless", "next", "nine",  "ninth", "no", "nobody", "none",
"nor", "nothing", "notwithstanding", "number",  "numbers", "of", "off", "on",
"once", "one", "onto", "opposite", "or", "other", "ought",  "our", "ours",
"ourselves", "out", "outside", "over", "part", "past", "pending", "per",
"pertaining", "place", "plenty", "plethora", "plus", "quantities", "quantity",
"quarter",  "regarding", "remainder", "respecting", "rest", "round", "save",
"saving", "second",  "seven", "seventh", "several", "shall", "she", "should",
"similar", "since", "six", "sixth",  "so", "some", "somebody", "someone",
"something", "spite", "such", "ten", "tenth",  "than", "thanks", "that", "the",
"their", "theirs", "them", "themselves", "then", "thence",  "therefore",
"these", "they", "third", "this", "those", "though", "three", "through",
"throughout", "thru", "thus", "till", "time", "to", "tons", "top", "toward",
"towards",  "two", "under", "underneath", "unless", "unlike", "until", "unto",
"up", "upon", "us",  "used", "various", "versus", "via", "view", "wanting",
"was", "we", "were", "what",  "whatever", "when", "whenever", "where",
"whereas", "wherever", "whether",  "which", "whichever", "while", "whilst",
"who", "whoever", "whole", "whom",  "whomever", "whose", "will", "with",
"within", "without", "would", "yet", "you",  "your", "yours", "yourself",
"yourselves"
])
